server:
  port: 8888
spring:
  profiles:
    active: native  # By default, use native (local) mode
---
# Profile for local development
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config
---
# Profile for use with Git repository
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaimerocha/travel-config-repo
          default-label: main